### ISSUE TITLE
opengalax and 0eef:725e D-WAV Scientific Co., Ltd

### ISSUE THREAD

**Issue by Qitek** [poliva/opengalax#3]
Hi, 

sorry if my question is stupid. I'm a beginner.

my son has Dell Inspiron 1090 with 0eef:725e D-WAV Scientific Co., Ltd touchscreen.
System: Debian Wheezy.
The touchscreen is connected to Bus 004 Device 002, I guess it's /dev/bus/usb/002/001 {no other file in that directory)

Wheezy unfortunately does not provide the evtouch package which is in Squeeze so I thought opengalax might enable it.

I installed it (successfully, I suppose) and ran:
sudo opengalax
then
sudo opengalax -c

BUT "Serial device /dev/serio_raw0 does not exist"

Can you please give me a hint or link how to configure opengalax correctly?

Thanx in advance.

Vit K.

**Comment by poliva** [comment]
The touchscreen should be available at /dev/hidraw[0-9], try running opengalax with parameter -s /dev/hidraw{NUM} and replace {NUM} by the appropriate file for your touchscreen.

**Comment by Qitek** [comment]
Unfortunately there is no hidraw\* in /dev (there was one but I realized it was a joystick) .
(It seems like there's no serial-connection to the touchscreen, only USB - sorry if I'm ignorant of something)

So how can I find the device-file location?
